name: SEND-COMMIT
on: workflow_dispatch
jobs:
  send-commit-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Send-Commit
        uses: ./.github/actions/docker
        id: send-commit
        with:
          commits-author: "usuario_prueba"
          source-repo-pull-request: "source-repo"
          target-repo: "repositorio destino"
          usuario: ${{ secrets.USUARIO }}
          user-pass: ${{ secrets.USER_PASS }}
      - name: Result
        run: echo ${{ steps.send-commit.outputs.result }}
