name: SEND-COMMIT
#on: workflow_dispatch
on:
  pull_request:
    types: [open]
jobs:
  send-commit-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Send-Commit
        uses: ./.github/actions/docker
        id: send-commit
        with:
          commits-author: "usuario_prueba"
          source-repo-pull-request: "source-repo"
          target-repo: "repositorio destino"
          usuario: ${{ secrets.USUARIO }}
          pull-number: ${{ github.event.issue.number }}
      - name: Result
        run: echo ${{ steps.send-commit.outputs.result }}
