name: SEND-COMMIT
#on: workflow_dispatch
on:
  workflow_dispatch:
  pull_request:
    types: 
      - opened
      - synchronize
      - edited
    branches:
      - develop
    
jobs:
  send-commit-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: branch_name
        run: |
          echo "BRANCH_NAME: ${{ github.head_ref || github.ref_name }}"
      - name: Send-Commit
        uses: ./.github/actions/docker
        id: send-commit
        with:
          commits-author: "usuario_prueba"
          source-repo-pull-request: "send-commit-action"
          target-repo: "send-commit-action-mirror"
          usuario: ${{ secrets.USUARIO }}
          pull-number: ${{ github.event.number }}
      - name: Result
        run: |
          echo ${{ steps.send-commit.outputs.result }}
#echo ${{ toJson(github) }}
